version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies (clean install)
          command: |
            npm ci
      - run:
          name: Run the tests
          command: npm run test
      - run:
          name: Build a production version of the React app
          command: npm run build

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
      - approve-deployment:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master